### ISSUE TITLE
21sh checklist

### ISSUE THREAD

**Issue by thijsdejong** [OscarMulder/codam-42sh#132]
# Requirements
- [x] The ctrl+D et ctrl+C keys combination features for line edition and process execution.
- [x] The “;” command line separator
- [x] Pipes “|”
- [x] The 4 following redirections “<”, “>”, “<<” et “>>”
- [x] File descriptor aggregation, for example to close the standard error output:
```
$> ls
riri
$> rm riri; cat riri 2>&-
```
Here is a representative example of commands your 21sh must be able to execute
correctly:
```
$> mkdir testdir ; cd testdir ; ls -a ; ls | cat | wc -c > fifi ; cat fifi
. ..
5
$>
```
- [x] It executes ✅

- [ ] A line edition feature using the termcaps library. Check the following description below:

Regarding the line edition, you must at least manage the following features. The
keys to be used are used as examples, you’re free to use other ones as long as your shell
remains logical and intuitive. The person evaluating you will decide what’s logical and
intuitive, so be careful not to get carried away with creativity.
- [x] Edit the line where the cursor is located.
- [x] Move the cursor left and right to be able to edit the line at a specific location. Obviously new characters have to be inserted between the existing ones similarly to a classic shell.
- [x] Use up and down arrows to navigate through the command history which we will then be able to edit if we feel like it (the line, not the history)
- [ ] Cut, copy, and/or paste all or part of a line using the key sequence you prefer.
- [x] Move directly by word towards the left or the right using ctrl+LEFT and ctrl+RIGHT or any other reasonable combination of keys.
- [x] Go directly to the beginning or the end of a line by pressing home and end.
- [x] Write AND edit a command over a few lines. In that case, we would love that ctrl+UP and ctrl+DOWN allow to go from one line to another in the command while remaining in the same column or otherwise the most appropriate column.
- [x] Completely manage quotes and double quotes, even on several lines (expansions excluded).
- [x] Fix (d)quote ctrl+d interaction.

# Allowed functions
- [ ] Check check double check ✅
◦ malloc, free
◦ access
◦ open, close, read, write
◦ opendir, readdir, closedir
◦ getcwd, chdir
◦ stat, lstat, fstat
◦ fork, execve
◦ wait, waitpid, wait3, wait4
◦ signal, kill
◦ exit
◦ pipe
◦ dup, dup2
◦ isatty, ttyname, ttyslot
◦ ioctl
◦ getenv
◦ tcsetattr, tcgetattr
◦ tgetent
◦ tgetflag
◦ tgetnum
◦ tgetstr
◦ tgoto
◦ tputs
