### ISSUE TITLE
42 checklist

### ISSUE THREAD

**Issue by marijnvanh** [OscarMulder/codam-42sh#140]
**Mandatory part**
- [x] builtin type
- [x] builtin export
- [x] builtin set
- [x] builtin unset
- [ ] builtin jobs, fg, bg, &
- [x] $ expansion
- [x] ${?} exit code of previous command

**Modular part 6/6**
- [x] Inhibitors ” (double quote), ’ (simple quote) and \
- [x] Complete management of the history:
    - [x] Expansions:
        - [x] !!
        - [x] !word
        - [x] !number
        - [x] !-number
    - [x] Saving to a file so that it can be used over several sessions
    - [x] Built-in fc (all POSIX options)
    - [x] Incremental search in the history with CTRL-R
- [ ] Pattern matching (globing): *, ?, [], ! and the caracters intervals with \ (backslash)
- [x] Alias management via built-ins alias and unalias
- [x] Contextual dynamic completion of commands, built-ins, files, internal and environment variables. What is meant by contextual? re-we use the “ls /” command and your cursor is on the /, then a contextual completion will only propose the content of the root folder and not the commands or built-ins. Same for this case: “echo ${S”, the completion should only propose variable names that start with S, whether internal or environmental.
- [x] A hash table and built-in hash to interact with it (FIX PROPER HASH FUNC)

**Bonus**
*Prerequisites*
- [x] No ternary every 3 lines.
- [ ] Explicit function names (no ft_parse1, ft_parse2, etc.)
- [ ] This also applies to variable names
- [ ] Use judiciously qualifer const
- [x] Have a git history and explicit commit messages
- [x] Have automated tests

*Actual Bonus*
- [ ] Autocompletion for order/built-ins parameters
